[watchman] fix windows build setuptools error
Summary:

The upgrade of setuptools in D79195099 broke pywatchman  build,  Github windows CI erroring with  `AttributeError: module 'setuptools.dist' has no attribute 'check_test_suite'` https://github.com/facebook/watchman/actions/runs/19440507973/job/55622405533#step:131:1188 .  It was only affecting windows as only windows CI is building dependencies form source, the others use system dependencies.

Fix by pinning watchman to the previous setuptools version

Once tests were running, that showed that test_bsdish.py and test_capabilities.py were timing out, so:
 * increase timeout on windows,
 * monitor suspend status by adding a status command to susres, rather than just assume

Couple of fixes to help iterate locally:
*  fix the cargo.py remove behaviour to use rmtree_more.  This fixes repeat local builds while debugging. After the first build was getting `PermissionError: [WinError 5] Access is denied: 'Z:\build\fbthrift\source\.git\objects\pack\pack-250eb41d409d8c0f512fdb239d0225fa35d50c3d.idx'`
* raise cmake min version to 3.19+ which has better python discovery, so that it doesn't pick 3.8 when 3.10 available

Test Plan:

python build/fbcode_builder/getdeps.py build --src-dir=. watchman --scratch-path='C:\s' --cmake-target=pywatchman

python build/fbcode_builder/getdeps.py test --src-dir=. watchman --scratch-path='C:\s'

CI